### PR TITLE
Code cleanup, PEP8 styling

### PR DESCRIPTION
**Pull request by JMY1000**
Still maybe have some work to do.

### CODE REVIEW

**Comment by lucapinello** [comment]
Thanks! one thing important is that the pip version of bluepy as a bug. This clone is working well https://github.com/lucapinello/bluepy . Do you know how to link in the setup.py a github repo?

**Comment by JMY1000** [comment]
Sorry, I'm not sure I understand what you're asking. Do you mean [dependency links?](https://python-packaging.readthedocs.io/en/latest/dependencies.html#packages-not-on-pypi)

**Comment by lucapinello** [comment]
Yes!

I didn't know about this option...

**Comment by JMY1000** [comment]
It seems like if you can avoid doing that and use the PIP version it'd be better. Could a release with the fix be issued maybe?

**Comment by lucapinello** [comment]
In theory yes, the problem is that the project has several pull requests
and not sure if it is maintained anymore at this point:
https://github.com/IanHarvey/bluepy

**Comment by JMY1000** [comment]
I see. Maybe the correct answer is just to fork and take over the project? Seems like that should be handed in another PR though.

**Comment by lucapinello** [comment]
Unfortunately, I don't have the bandwidth to take over this project so I
think the dependency links, for now, is the best option.

Thanks for taking the time to review my code!

Luca

**Pull request closed without merging**
